%YAML:1.0

BaseConfig:
  minDetectorConfidence: 0
  minTrackerConfidence: 0.4
  minMatchingScore4Overall: 0.0
  minTrailingScore4Alive: 0.6
  minHits4Tentative: 1
  minHits4Confirmed: 3
  maxShadowTrailingAge: 30
  probationAge: 3
  maxTargetAge: 150

TargetManagement:
  enableBboxUnClipping: 1
  preserveStreamUpdateOrder: 0
  maxTargetsPerStream: 150

TrajectoryManagement:
  useUniqueID: 0

DataAssociator:
  dataAssociatorType: 0
  associationMatcherType: 1
  checkClassMatch: 1

  minMatchingScore4Overall: 0.0
  minMatchingScore4SizeSimilarity: 0.5
  minMatchingScore4Appearance: 0.2

  matchingScoreWeight4SizeSimilarity: 60.0
  matchingScoreWeight4Appearance: 40.0

StateEstimator:
  stateEstimatorType: 2
  noiseWeightVar4Loc: 0.05
  noiseWeightVar4Vel: 0.00625

VisualTracker:
  visualTrackerType: 1
  useColorNames: 1
  useHog: 1
  featureImgSizeLevel: 3
